# Generated by Django 2.1.2 on 2018-12-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developer_id', models.AutoField(primary_key=True, serialize=False)),
                ('developer_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'developer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
                ('year_released', models.IntegerField(blank=True, null=True)),
                ('critic_score', models.IntegerField(blank=True, null=True)),
                ('critic_count', models.IntegerField(blank=True, null=True)),
                ('user_score', models.IntegerField(blank=True, null=True)),
                ('user_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameDeveloper',
            fields=[
                ('game_developer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'game_developer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_name', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
                ('platform_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year_released', models.CharField(blank=True, max_length=4, null=True)),
                ('genre_name', models.CharField(blank=True, max_length=25, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('north_america_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('europe_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('japan_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('global_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('critic_score', models.CharField(blank=True, max_length=3, null=True)),
                ('critic_count', models.CharField(blank=True, max_length=10, null=True)),
                ('user_score', models.CharField(blank=True, max_length=3, null=True)),
                ('user_count', models.CharField(blank=True, max_length=10, null=True)),
                ('developer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rating_name', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'temp_game',
                'managed': False,
            },
        ),
    ]
